build:
  version: "3.0"

accounts:
  message: "welcome to Eazy Bank account related local APIS"
  contactDetails:
    name: "Dennis Githinji"
    email: "wakahiad@gmail.com"
  onCallSupport:
    - "(555) 555-1234"
    - "(555) 523-1345"
