build:
  version: "2.0"

accounts:
  message: "welcome to easy Bank account related to qa APIS"
  contactDetails:
    name: "John Doe - QA Lead"
    email: "johndoe@gmail.com"
  onCallSupport:
    - "(666) 555-1234"
    - "(666) 523-1345"
